# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Committer < Formula
  desc "A tool to help you write better commit messages."
  homepage "https://github.com/ethn1ee/committer"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.10/committer_0.1.10_darwin_amd64.tar.gz"
      sha256 "bd2749d51a9be206344b404370741b62c12f36483fa89c6aa118c3c2ffd90a17"

      def install
        bin.install "committer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.10/committer_0.1.10_darwin_arm64.tar.gz"
      sha256 "87e1f2d4c18cda3b3e143bac5e707eb953009209530441af645cf5a10f574e03"

      def install
        bin.install "committer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.10/committer_0.1.10_linux_amd64.tar.gz"
      sha256 "69ab1b5874df199e775561abae4380f04e92368375f01d5dc7a7dc636a1772a6"
      def install
        bin.install "committer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.10/committer_0.1.10_linux_arm64.tar.gz"
      sha256 "92f730eacaf090572aa498e9e9d453f4f5036ae0fa9dc86465540b560795b157"
      def install
        bin.install "committer"
      end
    end
  end
end
