# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Committer < Formula
  desc "A tool to help you write better commit messages."
  homepage "https://github.com/ethn1ee/committer"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.9/committer_0.1.9_darwin_amd64.tar.gz"
      sha256 "82b9b58828fad18b335dc7b56a702abd34c7b67883af1bf8bcc875ad5c5f729c"

      def install
        bin.install "committer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.9/committer_0.1.9_darwin_arm64.tar.gz"
      sha256 "d215184b640a353e272e34131fd7699f5e02a5da79ee8609189ea5860cf20b52"

      def install
        bin.install "committer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.9/committer_0.1.9_linux_amd64.tar.gz"
      sha256 "d49fba81c7b00851b2201dc26b256a217ec97a1da22c6e7e64ee28186504bed2"
      def install
        bin.install "committer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.9/committer_0.1.9_linux_arm64.tar.gz"
      sha256 "2d93acc033c0a8fd3753dc0aae2398690cfd90f18ef703bd2a1243d8a43a8eeb"
      def install
        bin.install "committer"
      end
    end
  end
end
