# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Committer < Formula
  desc "A tool to help you write better commit messages."
  homepage "https://github.com/ethn1ee/committer"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.11/committer_0.1.11_darwin_amd64.tar.gz"
      sha256 "ebfff9cdf57683dfff6cc1f26e800295beea7a295644dc41db19f6a13c2829d3"

      def install
        bin.install "committer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.11/committer_0.1.11_darwin_arm64.tar.gz"
      sha256 "2eabb87eade4b9becd888156be01b50d0268e7800c0c9fd0e75b9469fea7d90f"

      def install
        bin.install "committer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.11/committer_0.1.11_linux_amd64.tar.gz"
      sha256 "2e9c101b479ef6bb4ce15f3a875a0365e9be964bb077938a4ccb777a5d15b908"
      def install
        bin.install "committer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ethn1ee/committer/releases/download/v0.1.11/committer_0.1.11_linux_arm64.tar.gz"
      sha256 "051c1ac6c13ea0bf544470e6274efefc8e0bcb626a35e5260b5214a2021ac804"
      def install
        bin.install "committer"
      end
    end
  end
end
