# This file was generated by GoReleaser. DO NOT EDIT.
cask "llog" do
  name "llog"
  desc "A simple life logger"
  homepage "https://github.com/ethn1ee/llog"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llog"

  on_macos do
    on_intel do
      url "https://github.com/ethn1ee/llog/releases/download/v#{version}/llog_#{version}_darwin_amd64.tar.gz"
      sha256 "55645f918a16c720991ddc6f6e6cf42b0f60e1684a163ac414894dd49b392711"
    end
    on_arm do
      url "https://github.com/ethn1ee/llog/releases/download/v#{version}/llog_#{version}_darwin_arm64.tar.gz"
      sha256 "974716ac89bab2043aad08a18ed6085cadf95b7ce289b8def302b1c196ff644f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ethn1ee/llog/releases/download/v#{version}/llog_#{version}_linux_amd64.tar.gz"
      sha256 "bf1de643f0c0ef87b688e18d6840da248d46ada84f8371c1bfe621457c2ae612"
    end
    on_arm do
      url "https://github.com/ethn1ee/llog/releases/download/v#{version}/llog_#{version}_linux_arm64.tar.gz"
      sha256 "5b892d2d5f970e13b0b3ea5c62539ea4e0b21a87fc3ad5752fa423907b66431c"
    end
  end

  # No zap stanza required
end
